services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: quant_user
      POSTGRES_PASSWORD: quant_pass
      POSTGRES_DB: quant_engine_db
    ports:
      - "5432:5432"
